### ISSUE TITLE
pointers: private mounts, getrandom, mmap•mlock, rollover, cluster-wide synchronization

### ISSUE THREAD

**Issue by mark-kubacki** [Fleshgrinder/nginx-session-ticket-key-rotation#1]
Moin!

I don't know if you've finished your M.Sc. thesis and are still able to incorporate some suggestions. Here they are anyway:

(1)
Most distributed systems in practice share memory through "distributed shared-memory". That is, a service synchronizes parts of memory you "mmap" as shared across processes on one machine. You could emulate (or discuss) that using the _Spread Toolkit_.
That memory needs to be encrypted, or its transport.

(2)
You can mount and remount parts of the filesystem as "private", rendering the files hard to access to other namespaces. (The knowledge will help you with Namespaces, systemd-nspawn, Docker, etc. btw.) Here's more on that: https://www.kernel.org/doc/Documentation/filesystems/sharedsubtree.txt

(3)
You don't need to mount tmpfs. _mmap_ with _mlock_ will do the trick. Modify Nginx if need be, it's trivial.

(4)
generate_key(): use Linux syscall "getrandom".

(5)
check_filesystem(): see command `findmnt`

(6)
check_ntpd(): Don't use _ntp_ at all. You need synchronized time, not accurate one. And you will be using TLS anyway. So you can just query any member of your cluster and obtain its time from the TLS handshake.

(7)
Nginx already obtains the system time for its own purposes every 100ms. You could just hook into that for key rollover, synchronizing using (6) if you have more than one machine.

I have completed my thesis at the DCSEC of the University of Hannover, btw. Good luck!

**Comment by Fleshgrinder** [comment]
Not yet, final exam is in June. But even if, I have no plans to abandon this project.
1. Looks interesting, but does not support shell.
2. The files and the file system are only accessible by root.
3. One of the main goals is **not to** modify nginx and hope that OpenSSL will provide all the functionality in the future.
4. Good point, should be better than `dd`.
5. Very good point.
6. My plan was to use a master server which will distribute the keys in the cluster and not multiple servers fetching the key. In this case I want accurate time on the master server and I actually don't care about the other servers in the cluster.
7. Not if I want to stay independent from nginx.

Many thanks for your input, it's highly appreciated! One of the main design goals was to use shell scripting because it allows any admin to read the source (and understand it) and to avoid any dependencies (e.g. Python). The most important design goal was not to hook into nginx in any way because (as mentioned before) the whole functionality provided by this script should be part of OpenSSL and not part of nginx (which is a server and has nothing to do with cryptography). I discussed these things beforehand in the nginx dev mailing list as well.

I once was in Bremen for half a year, studying at their University and Hochschule and a friend of mine is doing his master in Hamburg (which I highly prefer over Bremen).

Thanks and I'll release the complete thesis with an open license here on GitHub after the exam, in case you want to check it out.

**Comment by mark-kubacki** [comment]
I guess (based on my observations at some large companies and CDN providers) that the prevalent paradigm in distributed systems is pull, not push.

Nevertheless, you will figure everything out. ;-)

**Comment by Fleshgrinder** [comment]
I really do not know how they handle that, it was just my initial plan. I did not say that I'm not open to a pull system. I just thought that a push system is better because the root user of the master server has access to the other servers, but the other servers have no access to the master server. That was my reasoning behind the decision to prepare it for that.
